[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "django_project.settings_test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
python_classes = "Test*"
python_functions = "test_*"
addopts = "--strict-markers --tb=short"
testpaths = ["posts"]